lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'apa/', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^friend-list/$', friend_list, name='friend-list'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'^delete-friend/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list_json, name='get-friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
from django.views.generic import RedirectView
from lab_1.views import index as index_lab1

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include('lab_2_addon.urls', namespace='lab-2-addon')),
    url(r'^lab-3/', include('lab_3.urls', namespace='lab-3')),
    url(r'^lab-4/', include('lab_4.urls', namespace='lab-4')),
    url(r'^lab-5/', include('lab_5.urls', namespace='lab-5')),
    url(r'^lab-6/', include('lab_6.urls', namespace='lab-6')),
    url(r'^lab-7/', include('lab_7.urls', namespace='lab-7')),
    url(r'^lab-8/', include('lab_8.urls', namespace='lab-8')),
    url(r'^lab-9/', include('lab_9.urls', namespace='lab-9')),
    url(r'^lab-10/', include('lab_10.urls', namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='lab-10/', permanent='True')),
    url(r'^$', index_lab1, name='index'),
]

lab_7/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)
    alamat = models.CharField(max_length=250, null=True, blank=True)

    def as_dict(self):
        return {
            "friend_name": self.friend_name,
            "npm": self.npm,
        }

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os

from django.core import serializers

response = {}
csui_helper = CSUIhelper()

def index(request):
    page = request.GET.get('page', 1)
    mahasiswa_list, prev_url, next_url = csui_helper.instance.get_mahasiswa_list(page)

    friend_list = Friend.objects.all()
    html = 'lab_7/lab_7.html'

    response = {"mahasiswa_list": mahasiswa_list,
                "friend_list": friend_list,
                "prev_url": prev_url,
                "next_url": next_url,
                "page": page
                }
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_list_json(request): # update
    if request.method == 'GET':
        friends = [obj.as_dict() for obj in Friend.objects.all()]
        return JsonResponse({"results": friends}, content_type='application/json')

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        return JsonResponse(friend.as_dict())

@csrf_exempt
def delete_friend(request):
    if request.method == 'POST':
        npm = request.POST['npm']
        Friend.objects.filter(npm=npm).delete()
        return HttpResponseRedirect('/lab-7/friend-list/')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2>Fasilkom friends</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        var deleteFriend = function (npm) {
          $.ajax({
            method: "POST",
            url: '{% url "lab-7:delete-friend" %}',
            data: {
              npm: npm
                  },
            success: function(data){
              console.log(npm);
              $('#friend-'+npm).remove();
            },
            error: function (error){
              alert(error.responseText);
            }
          });
        }

        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-list' %}", // update
                success: function (response) {
                  console.log(response);
                  $.each(response['results'], function(index, friend){
                    console.log(friend);
                    var button = '<span class="pull-right">'+
                                    '<button type="button" class="btn btn-xs btn-danger"'+
                                    'onClick="deleteFriend' + "('"+friend.npm+"')"+ '">'+
                                        '&times;'+
                                    '</button>'+
                                 '</span>';

                    var html = '<a class="list-group-item clearfix" id="friend-' + friend.npm + '">'+
                                friend.friend_name +
                                ' (' + friend.npm + ')' + button + '</a>';
                    $("#friend-list").append(html)
                  });
                },
                error: function(error){
                    //tampilkan pesan error
                }
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                        <ul class="pager">
                            {% if prev_url %} <li><a href="?page={{ page|add:'-1' }}">Sebelumnya</a></li> {% endif %}
                            {% if next_url %} <li><a href="?page={{ page|add:'1' }}">Berikutnya</a></li> {% endif %}
                        </ul>
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: {
                    name: nama,
                    npm: npm
                  },
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name +
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert(error.responseText)
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}